### ISSUE TITLE
New PWA Builder is very slow???!! And is not working!! 

### ISSUE THREAD

**Issue by alleslatscho** [pwa-builder/pwabuilder-blog#25] opened 2021-07-08 23:52 UTC
Hello everybody, 

I've been using your site for a few month now and everything worked out super quickly. 

For 2 hours I want to convert a page into a PWA, it stops constantly and doesn't get any further, it stops when the manifest is being created.

Please reload the old PWA Builder version, the new one is no good. What do I have to do to properly create a PWA? 

Why did you renew it in the first place, the old one was much better. : - /

![Screenshot_20210709_014022](https://user-images.githubusercontent.com/87155757/125003746-2c4e3980-e058-11eb-9402-1fb17fafd7d9.jpg)

**Comment by JudahGabriel** [comment] 2021-07-09 22:54
Hi @alleslatscho 

Sorry you're hitting a problem with the new version. What you describe isn't the normal experience. 

To help diagnose this problem, can you tell me which URL you're using?

**Comment by JudahGabriel** [comment] 2021-07-10 00:06
Closing as duplicate of https://github.com/pwa-builder/PWABuilder/issues/1922#issuecomment-877465937

**Closed by JudahGabriel** 2021-07-10 00:06 UTC
